### ISSUE TITLE
Getting Server Error (500)

### ISSUE THREAD

**Issue by nerdfire01** [Software-Engineering-DHBW/BonoboBoard#83]
After trying to login to the bonoboboard i get redirected to the hompage https://bonoboboard.de/login/?next=/ and get a Server Errror 500.
As Login Details i tried my student e-mail, my corresponding password as well as the correct course.
Is this a known issue, and if so, could you help me to resolve it?

**Comment by Na1k** [comment]
![image](https://user-images.githubusercontent.com/61891241/160586110-1dbe9adc-2900-4784-b948-b83fef81c661.png)

**Comment by Na1k** [comment]
Resolved
